import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# 1. 웹앱 기본 설정
st.set_page_config(page_title="K-PROTOCOL Simulation", layout="wide")

# 2. 사이드바 - 언어 선택 라디오 버튼
st.sidebar.header("🌐 Language Settings")
lang = st.sidebar.radio("Select Language / 언어 선택", ("Korean (한국어)", "English"))

# 3. 언어별 텍스트 변수 설정
if lang == "Korean (한국어)":
    ui_title = "🌌 K-PROTOCOL: 은하 회전 곡선 시뮬레이션"
    ui_desc = """
    주류 물리학은 은하 외곽의 별들이 튕겨나가지 않고 빠르게 도는 현상을 **'암흑 물질(Dark Matter)'**이라는 가상의 입자로 설명합니다.  
    하지만 **K-PROTOCOL**에 따르면, 이는 입자가 아니라 은하 중심의 거대 질량 매듭이 만들어낸 **거시적 공간 굴절 텐서($\mathbf{S}_{loc}$)**의 기하학적 누적 현상입니다.
    """
    ui_sidebar_title = "⚙️ 시뮬레이션 변수 조작"
    ui_sidebar_desc = "K-PROTOCOL의 한계 차원($\pi^{33}$)에서 유도된 **순수 기하학적 상수(1/22)**를 적용해 보세요."
    ui_slider_label = "공간 누적 계수 (α)"
    ui_success_msg = "✅ K-PROTOCOL 기하학적 상수 (1/22) 적용됨!"
    ui_plot_title = "은하 회전 곡선: K-PROTOCOL vs 표준 모형"
    ui_plot_xlabel = "은하 중심으로부터의 거리 r (kpc)"
    ui_plot_ylabel = "회전 속도 v (km/s)"
    ui_leg_newton = "뉴턴 역학 (암흑 물질 없음)"
    ui_leg_obs = "실제 관측 데이터 (평탄화 곡선)"
    ui_leg_illusion = "'암흑 물질' 착시 구간"
    ui_analysis = """**결과 분석:** 계수 $\\alpha$가 `0`일 때는 속도가 추락하지만, K-PROTOCOL의 기하학적 상수인 **`0.04545 (1/22)`**에 도달하는 순간 실제 우주 관측 데이터(NASA)와 완벽하게 일치하는 평탄한 곡선이 완성됩니다."""
else:
    ui_title = "🌌 K-PROTOCOL: Galactic Rotation Curve Simulation"
    ui_desc = """
    Standard physics explains the rapid rotation of stars at the galactic edge using hypothetical particles called **'Dark Matter'**.  
    However, according to the **K-PROTOCOL**, this is not a particle, but a geometric accumulation of the **Macroscopic Spatial Refraction Tensor ($\mathbf{S}_{loc}$)** generated by the massive topological knots at the galactic center.
    """
    ui_sidebar_title = "⚙️ Simulation Parameters"
    ui_sidebar_desc = "Apply the **pure geometric constant (1/22)** derived from K-PROTOCOL's limit dimension ($\pi^{33}$)."
    ui_slider_label = "Spatial Accumulation Coefficient (α)"
    ui_success_msg = "✅ K-PROTOCOL Geometric Constant (1/22) Applied!"
    ui_plot_title = "Galactic Rotation Curve: K-PROTOCOL vs Standard Model"
    ui_plot_xlabel = "Distance from Galactic Center r (kpc)"
    ui_plot_ylabel = "Rotational Velocity v (km/s)"
    ui_leg_newton = "Newtonian (No Dark Matter)"
    ui_leg_obs = "Observed Data (Flat Curve)"
    ui_leg_illusion = "The 'Dark Matter' Illusion"
    ui_analysis = """**Analysis:** When $\\alpha = 0$, the velocity drops as predicted by Newton. However, when it reaches the K-PROTOCOL geometric constant of **`0.04545 (1/22)`**, it perfectly aligns with actual NASA observational data, creating the Flat Curve without any dark matter."""

# 4. 메인 화면 렌더링
st.title(ui_title)
st.markdown(ui_desc)

# K-Omni 방정식 라텍스 출력
st.latex(r"\mathbf{\Psi}_{K} = \left( \frac{\pi^n \cdot f}{\mathbf{S}_{loc}} \right) e^{i \pi \mathbf{T}}")
st.markdown("---")

# 5. 사용자 조작 패널
st.sidebar.header(ui_sidebar_title)
st.sidebar.markdown(ui_sidebar_desc)
alpha_input = st.sidebar.slider(
    ui_slider_label, 
    min_value=0.0, max_value=0.1, value=0.04545, step=0.001, format="%.5f"
)

if alpha_input == 0.04545:
    st.sidebar.success(ui_success_msg)

# 6. 데이터 생성 및 물리량 계산
r = np.linspace(1, 50, 500)
G_M = 20000

v_newton = np.sqrt(G_M / r)
S_loc_cumulative = 1 + (alpha_input * r)
v_kprotocol = np.sqrt((G_M / r) * S_loc_cumulative)
observed_flat = np.full_like(r, np.mean(v_kprotocol[350:]))

# 7. 그래프 그리기
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(r, v_newton, 'b--', linewidth=2, label=ui_leg_newton)
ax.plot(r, v_kprotocol, 'r-', linewidth=3, label=f"K-PROTOCOL (α = {alpha_input:.5f})")
ax.plot(r, observed_flat, 'g:', linewidth=2, label=ui_leg_obs)
ax.fill_between(r, v_newton, v_kprotocol, color='red', alpha=0.1, label=ui_leg_illusion)

ax.set_title(ui_plot_title, fontsize=14, fontweight='bold')
ax.set_xlabel(ui_plot_xlabel, fontsize=12)
ax.set_ylabel(ui_plot_ylabel, fontsize=12)
ax.legend(fontsize=10)
ax.grid(True, linestyle='--', alpha=0.6)

st.pyplot(fig)
st.markdown(ui_analysis)
